# This is the configuration used to lint and format the Ruby source code.
# See https://docs.rubocop.org/rubocop/configuration.html
#
# In addition to this global configuration, individual cops can be disabled locally as needed:
# https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code
#
# A full list of options can be found here:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
# https://docs.rubocop.org/rubocop/cops.html
# https://docs.rubocop.org/rubocop-rails/cops.html
#

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - bin/*
    - db/migrate/*.spree*.rb
    - db/schema.rb
    - vendor/bundle/**/*
    - vendor/data/**/*
    - node_modules/**/*
    - storefront/**/*
    - spree-storefront-api-v2-sdk/**/*
    - tmp/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*.rb
    - config/environments/development.rb
    - spec/rails_helper.rb

Metrics/MethodLength:
  Max: 12
  Exclude:
    - db/migrate/*.rb

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/UnknownEnv:
  Environments: development, pipeline, production, staging, test

Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - spec/**/*.rb
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
